#!/usr/bin/env bash
self=$(readlink -f $0); tasks=`dirname ${self}`; projectRoot=`dirname ${tasks}`;
docker build -t justinvanwinkle/utils:latest -t justinvanwinkle/utils:`date +%Y%m%d` -f Dockerfile.utils $projectRoot;



